name: Run Hello Postman Collection

on:
  push:
    branches: [ "main" ]

jobs:
  newman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Run Postman collection
        run: newman run hello_ci_cd.json -r cli,html --reporter-html-export hello-report.html

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-postman-report
          path: hello-report.html
