name: Post API Tests

on:
  push:
    branches:
      - main

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Post API tests
        run: newman run post_collection.json -r cli,htmlextra --reporter-htmlextra-export post-report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: Post-API-Report
          path: post-report.html
